//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemSpiderClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.chemspider.com/Search.asmx")]
        public string ChemSpiderClient_ChemSpiderSearch_Search {
            get {
                return ((string)(this["ChemSpiderClient_ChemSpiderSearch_Search"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatchTautomers {
            get {
                return ((bool)(this["MatchTautomers"]));
            }
            set {
                this["MatchTautomers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tanimoto")]
        public string SimilarityType {
            get {
                return ((string)(this["SimilarityType"]));
            }
            set {
                this["SimilarityType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.99")]
        public float SimilarityThreshold {
            get {
                return ((float)(this["SimilarityThreshold"]));
            }
            set {
                this["SimilarityThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExactMatch")]
        public string MatchType {
            get {
                return ((string)(this["MatchType"]));
            }
            set {
                this["MatchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Complexity {
            get {
                return ((string)(this["Complexity"]));
            }
            set {
                this["Complexity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Isotopic {
            get {
                return ((string)(this["Isotopic"]));
            }
            set {
                this["Isotopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasPatents {
            get {
                return ((bool)(this["HasPatents"]));
            }
            set {
                this["HasPatents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasSpectra {
            get {
                return ((bool)(this["HasSpectra"]));
            }
            set {
                this["HasSpectra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeAll {
            get {
                return ((bool)(this["IncludeAll"]));
            }
            set {
                this["IncludeAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncludeElements {
            get {
                return ((string)(this["IncludeElements"]));
            }
            set {
                this["IncludeElements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcludeElements {
            get {
                return ((string)(this["ExcludeElements"]));
            }
            set {
                this["ExcludeElements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FamilyMax {
            get {
                return ((string)(this["FamilyMax"]));
            }
            set {
                this["FamilyMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FamilyMin {
            get {
                return ((string)(this["FamilyMin"]));
            }
            set {
                this["FamilyMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ThresholdMax {
            get {
                return ((double)(this["ThresholdMax"]));
            }
            set {
                this["ThresholdMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ThresholdMin {
            get {
                return ((double)(this["ThresholdMin"]));
            }
            set {
                this["ThresholdMin"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("## This is the periodical table\r\n## One element is consisted by:\r\n## 1. Sequence " +
            "number\r\n## 2. Short name (abbrevation) \r\n## 3. Full name\r\n## 4. Relative atomic " +
            "mass (number)\r\n## 5. Brackets: 0 - no bracket, 1 - brackets are (true or false)\r" +
            "\n## 5. Color (in numbers from 1 to \r\n## 6. Position (x,y)\r\n## 7. Details (other " +
            "inforamtion about element) - \r\n##    better to create new file, which will have " +
            "only details of all elements\r\n##    or new file for each element!\r\n\r\n##---------" +
            "-----------------------\r\n\r\n##colors are:\r\n##1 - green\r\n##2 - blue\r\n##3 - orange\r" +
            "\n##4 - yellow\r\n##5 - dark green\r\n##6 - light blue (sky)\r\n##7 - gray\r\n##8 - red\r\n" +
            "##9 - pink\r\n##10- purple\r\n\r\n##Element list of all elements:\r\nELEMENT_LIST\r\n1\t-\tH" +
            "\t-\tHydrogen\t-\t1,0079\t\t-\t0\t-\t1\t-\t0x0\t-\tDetails…\r\n2\t-\tHe\t-\tHelium\t\t-\t4,0026\t\t-\t0\t-" +
            "\t2\t-\t17x0\t-\tDetails…\r\n3\t-\tLi\t-\tLithium\t\t-\t6,941\t\t-\t0\t-\t3\t-\t0x1\t-\tDetails…\r\n4\t-\tB" +
            "e\t-\tBeryllium\t-\t9,0122\t\t-\t0\t-\t4\t-\t1x1\t-\tDetails…\r\n5\t-\tB\t-\tBoron\t\t-\t10,811\t\t-\t0\t-" +
            "\t5\t-\t12x1\t-\tDetails…\r\n6\t-\tC\t-\tCarbon\t\t-\t12,0107\t\t-\t0\t-\t1\t-\t13x1\t-\tDetails…\r\n7\t-\t" +
            "N\t-\tNitrogen\t-\t14,0067\t\t-\t0\t-\t1\t-\t14x1\t-\tDetails…\r\n8\t-\tO\t-\tOxygen\t\t-\t15,9994\t\t-\t" +
            "0\t-\t1\t-\t15x1\t-\tDetails…\r\n9\t-\tF\t-\tFluorine\t-\t18,9984\t\t-\t0\t-\t6\t-\t16x1\t-\tDetails…\r\n" +
            "10\t-\tNe\t-\tNeon\t\t-\t20,1797\t\t-\t0\t-\t2\t-\t17x1\t-\tDetails…\r\n11\t-\tNa\t-\tSodium\t\t-\t22,989" +
            "7\t\t-\t0\t-\t3\t-\t0x2\t-\tDetails…\r\n12\t-\tMg\t-\tMagnesium\t-\t24,305\t\t-\t0\t-\t4\t-\t1x2\t-\tDetai" +
            "ls…\r\n13\t-\tAl\t-\tAluminum\t-\t26,9815\t\t-\t0\t-\t7\t-\t12x2\t-\tDetails…\r\n14\t-\tSi\t-\tSilicon\t" +
            "\t-\t28,0855\t\t-\t0\t-\t5\t-\t13x2\t-\tDetails…\r\n15\t-\tP\t-\tPhosphorus\t-\t30,9738\t\t-\t0\t-\t1\t-\t" +
            "14x2\t-\tDetails…\r\n16\t-\tS\t-\tSulfur\t\t-\t32,065\t\t-\t0\t-\t1\t-\t15x2\t-\tDetails…\r\n17\t-\tCl\t-" +
            "\tChlorine\t-\t35,453\t\t-\t0\t-\t6\t-\t16x2\t-\tDetails…\r\n18\t-\tAr\t-\tArgon\t\t-\t39,948\t\t-\t0\t-\t" +
            "2\t-\t17x2\t-\tDetails…\r\n19\t-\tK\t-\tPotassium\t-\t39,0983\t\t-\t0\t-\t3\t-\t0x3\t-\tDetails…\r\n20\t" +
            "-\tCa\t-\tCalcium\t\t-\t40,078\t\t-\t0\t-\t4\t-\t1x3\t-\tDetails…\r\n21\t-\tSc\t-\tScandium\t-\t44,9559" +
            "\t\t-\t0\t-\t8\t-\t2x3\t-\tDetails…\r\n22\t-\tTi\t-\tTitanium\t-\t47,867\t\t-\t0\t-\t8\t-\t3x3\t-\tDetails" +
            "…\r\n23\t-\tV\t-\tVanadium\t-\t50,9415\t\t-\t0\t-\t8\t-\t4x3\t-\tDetails…\r\n24\t-\tCr\t-\tChromium\t-\t5" +
            "1,9961\t\t-\t0\t-\t8\t-\t5x3\t-\tDetails…\r\n25\t-\tMn\t-\tManganese\t-\t54,938\t\t-\t0\t-\t8\t-\t6x3\t-\t" +
            "Details…\r\n26\t-\tFe\t-\tIron\t\t-\t55,845\t\t-\t0\t-\t8\t-\t7x3\t-\tDetails…\r\n27\t-\tCo\t-\tCobalt\t\t" +
            "-\t58,9332\t\t-\t0\t-\t8\t-\t8x3\t-\tDetails…\r\n28\t-\tNi\t-\tNickel\t\t-\t58,6934\t\t-\t0\t-\t8\t-\t9x3\t" +
            "-\tDetails…\r\n29\t-\tCu\t-\tCopper\t\t-\t63,546\t\t-\t0\t-\t8\t-\t10x3\t-\tDetails…\r\n30\t-\tZn\t-\tZin" +
            "c\t\t-\t65,39\t\t-\t0\t-\t8\t-\t11x3\t-\tDetails…\r\n31\t-\tGa\t-\tGallium\t\t-\t69,723\t\t-\t0\t-\t7\t-\t12" +
            "x3\t-\tDetails…\r\n32\t-\tGe\t-\tGermanium\t-\t72,64\t\t-\t0\t-\t5\t-\t13x3\t-\tDetails…\r\n33\t-\tAs\t-" +
            "\tArsenic\t\t-\t74,9216\t\t-\t0\t-\t5\t-\t14x3\t-\tDetails…\r\n34\t-\tSe\t-\tSelenium\t-\t78,96\t\t-\t0\t" +
            "-\t1\t-\t15x3\t-\tDetails…\r\n35\t-\tBr\t-\tBromine\t\t-\t79,904\t\t-\t0\t-\t6\t-\t16x3\t-\tDetails…\r\n3" +
            "6\t-\tKr\t-\tKrypton\t\t-\t83,8\t\t-\t0\t-\t2\t-\t17x3\t-\tDetails…\r\n37\t-\tRb\t-\tRubidium\t-\t85,467" +
            "8\t\t-\t0\t-\t3\t-\t0x4\t-\tDetails…\r\n38\t-\tSr\t-\tStrontium\t-\t87,62\t\t-\t0\t-\t4\t-\t1x4\t-\tDetail" +
            "s…\r\n39\t-\tY\t-\tYttrium\t\t-\t88,9059\t\t-\t0\t-\t8\t-\t2x4\t-\tDetails…\r\n40\t-\tZr\t-\tZirconium\t-" +
            "\t91,224\t\t-\t0\t-\t8\t-\t3x4\t-\tDetails…\r\n41\t-\tNb\t-\tNiobium\t\t-\t92,9064\t\t-\t0\t-\t8\t-\t4x4\t-" +
            "\tDetails…\r\n42\t-\tMo\t-\tMolybdenum\t-\t95,94\t\t-\t0\t-\t8\t-\t5x4\t-\tDetails…\r\n43\t-\tTc\t-\tTec" +
            "hnetium\t-\t98\t\t-\t1\t-\t8\t-\t6x4\t-\tDetails…\r\n44\t-\tRu\t-\tRuthenium\t-\t101,07\t\t-\t0\t-\t8\t-\t" +
            "7x4\t-\tDetails…\r\n45\t-\tRh\t-\tRhodium\t\t-\t102,9055\t-\t0\t-\t8\t-\t8x4\t-\tDetails…\r\n46\t-\tPd\t" +
            "-\tPalladium\t-\t106,42\t\t-\t0\t-\t8\t-\t9x4\t-\tDetails…\r\n47\t-\tAg\t-\tSilver\t\t-\t107,8682\t-\t0" +
            "\t-\t8\t-\t10x4\t-\tDetails…\r\n48\t-\tCd\t-\tCadmium\t\t-\t112,411\t\t-\t0\t-\t8\t-\t11x4\t-\tDetails…\r" +
            "\n49\t-\tIn\t-\tIndium\t\t-\t114,818\t\t-\t0\t-\t7\t-\t12x4\t-\tDetails…\r\n50\t-\tSn\t-\tTin\t\t-\t118,71" +
            "\t\t-\t0\t-\t7\t-\t13x4\t-\tDetails…\r\n51\t-\tSb\t-\tAntimony\t-\t121,76\t\t-\t0\t-\t5\t-\t14x4\t-\tDetai" +
            "ls…\r\n52\t-\tTe\t-\tTellurium\t-\t127,6\t\t-\t0\t-\t5\t-\t15x4\t-\tDetails…\r\n53\t-\tI\t-\tIodine\t\t-\t" +
            "126,9045\t-\t0\t-\t6\t-\t16x4\t-\tDetails…\r\n54\t-\tXe\t-\tXenon\t\t-\t131,293\t\t-\t0\t-\t2\t-\t17x4\t-" +
            "\tDetails…\r\n55\t-\tCs\t-\tCesium\t\t-\t132,9055\t-\t0\t-\t3\t-\t0x5\t-\tDetails…\r\n56\t-\tBa\t-\tBari" +
            "um\t\t-\t137,327\t\t-\t0\t-\t4\t-\t1x5\t-\tDetails…\r\n57\t-\tLa\t-\tLanthanum\t-\t138,9055\t-\t0\t-\t8\t" +
            "-\t2x5\t-\tDetails…\r\n58\t-\tCe\t-\tCerium\t\t-\t140,116\t\t-\t0\t-\t9\t-\t2x8\t-\tDetails…\r\n59\t-\tPr" +
            "\t-\tPraseodymium\t-\t140,9077\t-\t0\t-\t9\t-\t3x8\t-\tDetails…\r\n60\t-\tNd\t-\tNeodymium\t-\t144,2" +
            "4\t\t-\t0\t-\t9\t-\t4x8\t-\tDetails…\r\n61\t-\tPm\t-\tPromethium\t-\t145\t\t-\t1\t-\t9\t-\t5x8\t-\tDetails" +
            "…\r\n62\t-\tSm\t-\tSamarium\t-\t150,36\t\t-\t0\t-\t9\t-\t6x8\t-\tDetails…\r\n63\t-\tEu\t-\tEuropium\t-\t1" +
            "51,964\t\t-\t0\t-\t9\t-\t7x8\t-\tDetails…\r\n64\t-\tGd\t-\tGadolinium\t-\t157,25\t\t-\t0\t-\t9\t-\t8x8\t-" +
            "\tDetails…\r\n65\t-\tTb\t-\tTerbium\t\t-\t158,9253\t-\t0\t-\t9\t-\t9x8\t-\tDetails…\r\n66\t-\tDy\t-\tDys" +
            "prosium\t-\t162,5\t\t-\t0\t-\t9\t-\t10x8\t-\tDetails…\r\n67\t-\tHo\t-\tHolmium\t\t-\t164,9303\t-\t0\t-\t" +
            "9\t-\t11x8\t-\tDetails…\r\n68\t-\tEr\t-\tErbium\t\t-\t167,259\t\t-\t0\t-\t9\t-\t12x8\t-\tDetails…\r\n69\t" +
            "-\tTm\t-\tThulium\t\t-\t168,9342\t-\t0\t-\t9\t-\t13x8\t-\tDetails…\r\n70\t-\tYb\t-\tYtterbium\t-\t173," +
            "04\t\t-\t0\t-\t9\t-\t14x8\t-\tDetails…\r\n71\t-\tLu\t-\tLutetium\t-\t174,967\t\t-\t0\t-\t9\t-\t15x8\t-\tDe" +
            "tails…\r\n72\t-\tHf\t-\tHafnium\t\t-\t178,49\t\t-\t0\t-\t8\t-\t3x5\t-\tDetails…\r\n73\t-\tTa\t-\tTantalu" +
            "m\t-\t180,9479\t-\t0\t-\t8\t-\t4x5\t-\tDetails…\r\n74\t-\tW\t-\tTungsten\t-\t183,84\t\t-\t0\t-\t8\t-\t5x5" +
            "\t-\tDetails…\r\n75\t-\tRe\t-\tRhenium\t\t-\t186,207\t\t-\t0\t-\t8\t-\t6x5\t-\tDetails…\r\n76\t-\tOs\t-\tO" +
            "smium\t\t-\t190,23\t\t-\t0\t-\t8\t-\t7x5\t-\tDetails…\r\n77\t-\tIr\t-\tIridium\t\t-\t192,217\t\t-\t0\t-\t8" +
            "\t-\t8x5\t-\tDetails…\r\n78\t-\tPt\t-\tPlatinum\t-\t195,078\t\t-\t0\t-\t8\t-\t9x5\t-\tDetails…\r\n79\t-\t" +
            "Au\t-\tGold\t\t-\t196,9665\t-\t0\t-\t8\t-\t10x5\t-\tDetails…\r\n80\t-\tHg\t-\tMercury\t\t-\t200,59\t\t-\t" +
            "0\t-\t8\t-\t11x5\t-\tDetails…\r\n81\t-\tTl\t-\tThallium\t-\t204,3833\t-\t0\t-\t7\t-\t12x5\t-\tDetails…" +
            "\r\n82\t-\tPb\t-\tLead\t\t-\t207,2\t\t-\t0\t-\t7\t-\t13x5\t-\tDetails…\r\n83\t-\tBi\t-\tBismuth\t\t-\t208,9" +
            "804\t-\t0\t-\t7\t-\t14x5\t-\tDetails…\r\n84\t-\tPo\t-\tPolonium\t-\t209\t\t-\t1\t-\t5\t-\t15x5\t-\tDetail" +
            "s…\r\n85\t-\tAt\t-\tAstatine\t-\t210\t\t-\t1\t-\t6\t-\t16x5\t-\tDetails…\r\n86\t-\tRn\t-\tRadon\t\t-\t222\t" +
            "\t-\t1\t-\t2\t-\t17x5\t-\tDetails…\r\n87\t-\tFr\t-\tFrancium\t-\t223\t\t-\t1\t-\t3\t-\t0x6\t-\tDetails…\r\n" +
            "88\t-\tRa\t-\tRadium\t\t-\t226\t\t-\t1\t-\t4\t-\t1x6\t-\tDetails…\r\n89\t-\tAc\t-\tActinium\t-\t227\t\t-\t1" +
            "\t-\t8\t-\t2x6\t-\tDetails…\r\n90\t-\tTh\t-\tThorium\t\t-\t232,0381\t-\t0\t-\t10\t-\t2x9\t-\tDetails…\r\n" +
            "91\t-\tPa\t-\tProtactinium\t-\t231,0359\t-\t0\t-\t10\t-\t3x9\t-\tDetails…\r\n92\t-\tU\t-\tUranium\t\t-" +
            "\t238,0289\t-\t0\t-\t10\t-\t4x9\t-\tDetails…\r\n93\t-\tNp\t-\tNeptunium\t-\t237\t\t-\t1\t-\t10\t-\t5x9\t-" +
            "\tDetails…\r\n94\t-\tPu\t-\tPlutonium\t-\t244\t\t-\t1\t-\t10\t-\t6x9\t-\tDetails…\r\n95\t-\tAm\t-\tAmeri" +
            "cium\t-\t243\t\t-\t1\t-\t10\t-\t7x9\t-\tDetails…\r\n96\t-\tCm\t-\tCurium\t\t-\t247\t\t-\t1\t-\t10\t-\t8x9\t-" +
            "\tDetails…\r\n97\t-\tBk\t-\tBerkelium\t-\t247\t\t-\t1\t-\t10\t-\t9x9\t-\tDetails…\r\n98\t-\tCf\t-\tCalif" +
            "ornium\t-\t251\t\t-\t1\t-\t10\t-\t10x9\t-\tDetails…\r\n99\t-\tEs\t-\tEinsteinium\t-\t252\t\t-\t1\t-\t10\t" +
            "-\t11x9\t-\tDetails…\r\n100\t-\tFm\t-\tFermium\t\t-\t257\t\t-\t1\t-\t10\t-\t12x9\t-\tDetails…\r\n101\t-\t" +
            "Md\t-\tMendelevium\t-\t258\t\t-\t1\t-\t10\t-\t13x9\t-\tDetails…\r\n102\t-\tNo\t-\tNobelium\t-\t259\t\t-" +
            "\t1\t-\t10\t-\t14x9\t-\tDetails…\r\n103\t-\tLr\t-\tLawrencium\t-\t262\t\t-\t1\t-\t10\t-\t15x9\t-\tDetail" +
            "s…\r\n104\t-\tRf\t-\tRutherfordium\t-\t261\t\t-\t1\t-\t8\t-\t3x6\t-\tDetails…\r\n105\t-\tDb\t-\tDubnium" +
            "\t\t-\t262\t\t-\t1\t-\t8\t-\t4x6\t-\tDetails…\r\n106\t-\tSg\t-\tSeaborgium\t-\t266\t\t-\t1\t-\t8\t-\t5x6\t-\t" +
            "Details…\r\n107\t-\tBh\t-\tBohrium\t\t-\t264\t\t-\t1\t-\t8\t-\t6x6\t-\tDetails…\r\n108\t-\tHs\t-\tHassiu" +
            "m\t\t-\t277\t\t-\t1\t-\t8\t-\t7x6\t-\tDetails…\r\n109\t-\tMt\t-\tMeitnerium\t-\t268\t\t-\t1\t-\t8\t-\t8x6\t-" +
            "\tDetails…\r\n110\t-\tDs\t-\tDarmstadtium\t-\t271\t\t-\t1\t-\t8\t-\t9x6\t-\tDetails…\r\n111\t-\tRg\t-\tR" +
            "oentgenium\t-\t272\t\t-\t1\t-\t8\t-\t10x6\t-\tDetails…\r\n112\t-\tUnb\t-\tCopernicium\t-\t285\t\t-\t1\t" +
            "-\t8\t-\t11x6\t-\tDetails…\r\n113\t-\tUnt\t-\tUnuntrium\t-\t284\t\t-\t1\t-\t7\t-\t12x6\t-\tDetails…\r\n1" +
            "14\t-\tUnq\t-\tUnunquadium\t-\t289\t\t-\t1\t-\t7\t-\t13x6\t-\tDetails…\r\n115\t-\tUnp\t-\tUnunpentium" +
            "\t-\t288\t\t-\t1\t-\t7\t-\t14x6\t-\tDetails…\r\n116\t-\tUnh\t-\tUnunhexium\t-\t292\t\t-\t1\t-\t7\t-\t15x6\t" +
            "-\tDetails…\r\n117\t-\tUns\t-\tUnunseptium\t-\t295\t\t-\t1\t-\t6\t-\t16x6\t-\tDetails…\r\n118\t-\tUno\t" +
            "-\tUnunoctium\t-\t294\t\t-\t1\t-\t2\t-\t17x6\t-\tDetails…\r\n\r\n\r\n\r\n\r\n##Legend\r\nLEGEND\r\n## lege" +
            "nds is consisted of color (number of color), name of group and location (x,y)\r\n1" +
            "\t-\tNon metals\t\t-\t5,8x1,2\r\n2\t-\tNoble gases\t\t-\t9x0,6\r\n3\t-\tAlkal metal\t\t-\t2,5x0\r\n4\t" +
            "-\tAlkaline earth metal\t-\t2,5x0,6\r\n5\t-\tMetalloids\t\t-\t5,8x0,6\r\n6\t-\tHalogens\t\t-\t9x0" +
            "\r\n7\t-\tPoor metals\t\t-\t5,8x0\r\n8\t-\tTrasnmition metlas\t-\t2,5x1,2\r\n9\t-\tLanthanides\t\t-" +
            "\t9x1,2\r\n10\t-\tActinides\t\t-\t9x1,8")]
        public string Elements {
            get {
                return ((string)(this["Elements"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.chemspider.com/InChI.asmx")]
        public string ChemSpiderClient_ChemSpiderInChI_InChI {
            get {
                return ((string)(this["ChemSpiderClient_ChemSpiderInChI_InChI"]));
            }
        }
    }
}
